### ISSUE TITLE
魔趣rom 安卓10无法显示歌词

### ISSUE THREAD

**Issue by Young-Lord** [577fkj/StatusBarLyric#135]
**环境信息**

模块版本: 3.56.25
MIUI版本: （类原生）魔趣ROM MK100.0-gemini-210921-RELEASE（可提供SystemUI apk）
Android版本: 10
屏幕类型: 全面屏

**在最新的release版本中能否复现**
能（3.56.25）

**bug内容**
无法显示歌词

**复现方法**
正常使用

**LOG**
```
----part 1 start----
[ 2022-01-22T21:36:04.178    10217:  8457:  8457 I/LSPosed-Bridge  ] Loading module miui.statusbar.lyric from /data/app/miui.statusbar.lyric-HKJNfxV5hEYlzB9R7ec6GA==/base.apk
[ 2022-01-22T21:36:04.190    10217:  8457:  8457 I/LSPosed-Bridge  ]   Loading class miui.statusbar.lyric.hook.MainHook
[ 2022-01-22T21:36:04.305    10217:  8457:  8457 I/LSPosed-Bridge  ] StatusBarLyric: Hook android.app.Application.attach Successful
[ 2022-01-22T21:36:04.307    10217:  8457:  8457 I/LSPosed-Bridge  ] StatusBarLyric: Debug已开启
[ 2022-01-22T21:36:04.307    10217:  8457:  8457 I/LSPosed-Bridge  ] StatusBarLyric: miui.statusbar.lyric - 3.56.25(83 *release)
[ 2022-01-22T21:36:04.308    10217:  8457:  8457 I/LSPosed-Bridge  ] StatusBarLyric: 当前包名: miui.statusbar.lyric
[ 2022-01-22T21:36:46.410    10120:  8778:  8778 I/LSPosed-Bridge  ] Loading module com.darkeyes.tricks from /data/app/com.darkeyes.tricks-SVVlx7taySVbC5rsreMjpA==/base.apk
[ 2022-01-22T21:36:46.514    10120:  8778:  8778 I/LSPosed-Bridge  ]   Loading class com.darkeyes.tricks.Main
[ 2022-01-22T21:36:46.553    10120:  8778:  8778 I/LSPosed-Bridge  ] Loading module miui.statusbar.lyric from /data/app/miui.statusbar.lyric-HKJNfxV5hEYlzB9R7ec6GA==/base.apk
[ 2022-01-22T21:36:46.561    10120:  8778:  8778 I/LSPosed-Bridge  ]   Loading class miui.statusbar.lyric.hook.MainHook
[ 2022-01-22T21:36:48.417    10120:  8778:  8778 E/LSPosed-Bridge  ] java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ImageView.setImageTintList(android.content.res.ColorStateList)' on a null object reference
	at 截图看NM日志.今坠.afterHookedMethod(:2)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:136)
	at LspHooker_.getTint(Unknown Source:18)
	at com.android.systemui.statusbar.policy.Clock.onDarkChanged(Clock.java:328)
	at com.android.systemui.statusbar.phone.DarkIconDispatcherImpl.addDarkReceiver(DarkIconDispatcherImpl.java:67)
	at com.android.systemui.statusbar.policy.Clock.onAttachedToWindow(Clock.java:195)
	at android.view.View.dispatchAttachedToWindow(View.java:20123)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3437)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2049)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1742)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7770)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
	at android.view.Choreographer.doCallbacks(Choreographer.java:791)
	at android.view.Choreographer.doFrame(Choreographer.java:726)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
```

**Comment by Young-Lord** [comment]
SystemUI：
https://wwe.lanzouo.com/i7PAiz4t01e
密码:afcb

**Comment by 577fkj** [comment]
请发完整日志

**Comment by Young-Lord** [comment]
> 请发完整日志

[LSPosed_2022-02-06T20:11:35.458.zip](https://github.com/577fkj/StatusBarLyric/files/8010152/LSPosed_2022-02-06T20.11.35.458.zip)

抱歉回复的这么晚

版本更新到了4.0.0(100)-release，依然是没有显示歌词

**Comment by 577fkj** [comment]
> > 请发完整日志
> 
> [LSPosed_2022-02-06T20:11:35.458.zip](https://github.com/577fkj/StatusBarLyric/files/8010152/LSPosed_2022-02-06T20.11.35.458.zip)
> 
> 抱歉回复的这么晚
> 
> 版本更新到了4.0.0(100)-release，依然是没有显示歌词
> 
> 大概看了一下，貌似是因为`ClockController`的构造函数只接受一个类型为`android.view.View`的参数导致的异常

最新ci修复了

**Comment by Young-Lord** [comment]
> 最新ci修复了

刚才测试了，安装ci的版本后并重启手机后，依旧会报同样的NoSuchMethodError（在第666行，也就是参数列表中有Context的）；但反编译安装包并把第一个hookConstructor改成和第二个一样（也就是都只有View），就能正常使用了

**Comment by 577fkj** [comment]
> > 最新ci修复了
> 
> 刚才测试了，安装ci的版本后并重启手机后，依旧会报同样的NoSuchMethodError（在第666行，也就是参数列表中有Context的）；但反编译安装包并把第一个hookConstructor改成和第二个一样（也就是都只有View），就能显示歌词了

 应该是try没拦截到 我等会修一下

**Comment by 577fkj** [comment]
> > 最新ci修复了
> 
> 刚才测试了，安装ci的版本后并重启手机后，依旧会报同样的NoSuchMethodError（在第666行，也就是参数列表中有Context的）；但反编译安装包并把第一个hookConstructor改成和第二个一样（也就是都只有View），就能显示歌词了

最新ci已经修复

**Comment by Young-Lord** [comment]
> 最新ci已经修复

相同情况

**Comment by 577fkj** [comment]
> > 最新ci已经修复
> 
> 相同情况

进一下tg群吧 https://t.me/+z5f5RVaA-p0zY2Nh
