### ISSUE TITLE
能正常显示测试歌词，但无法显示酷我（修改版）歌词

### ISSUE THREAD

**Issue by Eric-Joker** [577fkj/StatusBarLyric#144]
**环境信息**

模块版本: 4.0.0
MIUI版本: 12.5 21.12.8
Android版本: 11
屏幕类型: 挖孔屏

**在最新的release版本中能否复现**
能
**bug内容**

能正常显示测试歌词，但无法显示自行修改后的酷我音乐的歌词，确认车载蓝牙歌词已打开
**复现方法**

正常使用。

日志：
[ 2022-02-11T21:11:25.204    10362: 21134: 21134 I/LSPosed-Bridge  ] StatusBarLyric: Debug已开启
[ 2022-02-11T21:11:25.204    10362: 21134: 21134 I/LSPosed-Bridge  ] StatusBarLyric: statusbar.lyric - 4.0.0(100 *release)
[ 2022-02-11T21:11:25.204    10362: 21134: 21134 I/LSPosed-Bridge  ] StatusBarLyric: 当前包名: cn.kuwo.player
[ 2022-02-11T21:11:25.204    10362: 21134: 21134 I/LSPosed-Bridge  ] StatusBarLyric: 正在hook酷我音乐
[ 2022-02-11T21:11:25.210    10362: 21134: 21134 I/LSPosed-Bridge  ] StatusBarLyric: Hook android.bluetooth.BluetoothAdapter.isEnabled Successful
[ 2022-02-11T21:11:25.216    10362: 21134: 21134 I/LSPosed-Bridge  ] StatusBarLyric: de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: cn.kuwo.mod.playcontrol.RemoteControlLyricMgr
	at de.robv.android.xposed.XposedHelpers.findClass(Unknown Source:13)
	at 截图看NM日志.席.晴(:21)
	at statusbar.lyric.hook.MainHook.handleLoadPackage(:28)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at de.robv.android.xposed.callbacks.XCallback.callAll(Unknown Source:28)
	at L.afterHookedMethod(Unknown Source:111)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:136)
	at LspHooker_.getClassLoader(Unknown Source:8)
	at android.app.LoadedApk.getResources(LoadedApk.java:1195)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:2671)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:2663)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6944)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:107)
	at LspHooker_.handleBindApplication(Unknown Source:11)
	at android.app.ActivityThread.access$1500(ActivityThread.java:264)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2020)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8168)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: java.lang.ClassNotFoundException: cn.kuwo.mod.playcontrol.RemoteControlLyricMgr
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:454)
	at m.a(Unknown Source:24)
	at de.robv.android.xposed.XposedHelpers.findClass(Unknown Source:5)
	... 23 more
Caused by: java.lang.ClassNotFoundException: cn.kuwo.mod.playcontrol.RemoteControlLyricMgr
	... 27 more
[ 2022-02-11T21:11:25.216    10362: 21134: 21134 I/LSPosed-Bridge  ] StatusBarLyric: hook酷我音乐结束
[ 2022-02-11T21:11:29.014    10362: 21134: 21362 I/LSPosed-Bridge  ] StatusBarLyric: Hook android.app.Application.attach Successful

**Comment by 577fkj** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by qqlittleice233** [comment]
未修改的包是否能正常使用?
根据你的描述，应该是你自己修改了包，从模块日志中得知是模块未找到类，请确保你没改动模块所hook的类。

**Comment by qqlittleice233** [comment]
no response, closed

**Comment by smresultwithout** [comment]
同样遇到了，用的网上下载的修改版，
